// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: api/opcda/v1/opcda_access.proto

package opcdav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DABrowseFilter int32

const (
	DABrowseFilter_DA_BROWSE_FILTER_ALL    DABrowseFilter = 0
	DABrowseFilter_DA_BROWSE_FILTER_BRANCH DABrowseFilter = 1
	DABrowseFilter_DA_BROWSE_FILTER_ITEM   DABrowseFilter = 2
)

// Enum value maps for DABrowseFilter.
var (
	DABrowseFilter_name = map[int32]string{
		0: "DA_BROWSE_FILTER_ALL",
		1: "DA_BROWSE_FILTER_BRANCH",
		2: "DA_BROWSE_FILTER_ITEM",
	}
	DABrowseFilter_value = map[string]int32{
		"DA_BROWSE_FILTER_ALL":    0,
		"DA_BROWSE_FILTER_BRANCH": 1,
		"DA_BROWSE_FILTER_ITEM":   2,
	}
)

func (x DABrowseFilter) Enum() *DABrowseFilter {
	p := new(DABrowseFilter)
	*p = x
	return p
}

func (x DABrowseFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DABrowseFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_api_opcda_v1_opcda_access_proto_enumTypes[0].Descriptor()
}

func (DABrowseFilter) Type() protoreflect.EnumType {
	return &file_api_opcda_v1_opcda_access_proto_enumTypes[0]
}

func (x DABrowseFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DABrowseFilter.Descriptor instead.
func (DABrowseFilter) EnumDescriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{0}
}

type DABrowseEntryKind int32

const (
	DABrowseEntryKind_DA_BROWSE_ENTRY_KIND_UNSPECIFIED DABrowseEntryKind = 0
	DABrowseEntryKind_DA_BROWSE_ENTRY_KIND_BRANCH      DABrowseEntryKind = 1
	DABrowseEntryKind_DA_BROWSE_ENTRY_KIND_ITEM        DABrowseEntryKind = 2
)

// Enum value maps for DABrowseEntryKind.
var (
	DABrowseEntryKind_name = map[int32]string{
		0: "DA_BROWSE_ENTRY_KIND_UNSPECIFIED",
		1: "DA_BROWSE_ENTRY_KIND_BRANCH",
		2: "DA_BROWSE_ENTRY_KIND_ITEM",
	}
	DABrowseEntryKind_value = map[string]int32{
		"DA_BROWSE_ENTRY_KIND_UNSPECIFIED": 0,
		"DA_BROWSE_ENTRY_KIND_BRANCH":      1,
		"DA_BROWSE_ENTRY_KIND_ITEM":        2,
	}
)

func (x DABrowseEntryKind) Enum() *DABrowseEntryKind {
	p := new(DABrowseEntryKind)
	*p = x
	return p
}

func (x DABrowseEntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DABrowseEntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_opcda_v1_opcda_access_proto_enumTypes[1].Descriptor()
}

func (DABrowseEntryKind) Type() protoreflect.EnumType {
	return &file_api_opcda_v1_opcda_access_proto_enumTypes[1]
}

func (x DABrowseEntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DABrowseEntryKind.Descriptor instead.
func (DABrowseEntryKind) EnumDescriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{1}
}

type DADataSource int32

const (
	DADataSource_DA_DATA_SOURCE_DEVICE DADataSource = 0
)

// Enum value maps for DADataSource.
var (
	DADataSource_name = map[int32]string{
		0: "DA_DATA_SOURCE_DEVICE",
	}
	DADataSource_value = map[string]int32{
		"DA_DATA_SOURCE_DEVICE": 0,
	}
)

func (x DADataSource) Enum() *DADataSource {
	p := new(DADataSource)
	*p = x
	return p
}

func (x DADataSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DADataSource) Descriptor() protoreflect.EnumDescriptor {
	return file_api_opcda_v1_opcda_access_proto_enumTypes[2].Descriptor()
}

func (DADataSource) Type() protoreflect.EnumType {
	return &file_api_opcda_v1_opcda_access_proto_enumTypes[2]
}

func (x DADataSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DADataSource.Descriptor instead.
func (DADataSource) EnumDescriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{2}
}

type DAAvailableItemPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAAvailableItemPropertiesRequest) Reset() {
	*x = DAAvailableItemPropertiesRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAAvailableItemPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAAvailableItemPropertiesRequest) ProtoMessage() {}

func (x *DAAvailableItemPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAAvailableItemPropertiesRequest.ProtoReflect.Descriptor instead.
func (*DAAvailableItemPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{0}
}

func (x *DAAvailableItemPropertiesRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type DAAvailableItemPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Properties    []*DAAvailableProperty `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAAvailableItemPropertiesResponse) Reset() {
	*x = DAAvailableItemPropertiesResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAAvailableItemPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAAvailableItemPropertiesResponse) ProtoMessage() {}

func (x *DAAvailableItemPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAAvailableItemPropertiesResponse.ProtoReflect.Descriptor instead.
func (*DAAvailableItemPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{1}
}

func (x *DAAvailableItemPropertiesResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DAAvailableItemPropertiesResponse) GetProperties() []*DAAvailableProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

// DAAvailableProperty is one property a source reports for an item. The
// description is the server's own text, passed through unchanged.
type DAAvailableProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    uint32                 `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DataType      *DAVarType             `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAAvailableProperty) Reset() {
	*x = DAAvailableProperty{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAAvailableProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAAvailableProperty) ProtoMessage() {}

func (x *DAAvailableProperty) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAAvailableProperty.ProtoReflect.Descriptor instead.
func (*DAAvailableProperty) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{2}
}

func (x *DAAvailableProperty) GetPropertyId() uint32 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *DAAvailableProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DAAvailableProperty) GetDataType() *DAVarType {
	if x != nil {
		return x.DataType
	}
	return nil
}

type DAItemPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	PropertyIds   []uint32               `protobuf:"varint,2,rep,packed,name=property_ids,json=propertyIds,proto3" json:"property_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAItemPropertiesRequest) Reset() {
	*x = DAItemPropertiesRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAItemPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAItemPropertiesRequest) ProtoMessage() {}

func (x *DAItemPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAItemPropertiesRequest.ProtoReflect.Descriptor instead.
func (*DAItemPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{3}
}

func (x *DAItemPropertiesRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DAItemPropertiesRequest) GetPropertyIds() []uint32 {
	if x != nil {
		return x.PropertyIds
	}
	return nil
}

type DAItemPropertiesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ItemId        string                  `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Results       []*DAItemPropertyResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAItemPropertiesResponse) Reset() {
	*x = DAItemPropertiesResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAItemPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAItemPropertiesResponse) ProtoMessage() {}

func (x *DAItemPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAItemPropertiesResponse.ProtoReflect.Descriptor instead.
func (*DAItemPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{4}
}

func (x *DAItemPropertiesResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DAItemPropertiesResponse) GetResults() []*DAItemPropertyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DAItemPropertyResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PropertyId uint32                 `protobuf:"varint,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Ok         bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	DataType   *DAVarType             `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Value      *DAScalarValue         `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Hresult    *DAHRESULT             `protobuf:"bytes,5,opt,name=hresult,proto3" json:"hresult,omitempty"`
	ErrorCode  string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Whether a value is carried. A source can answer a property successfully
	// and give nothing -- an empty VARIANT is an answer. Presence is its own bit
	// for the same reason a Read timestamp's is: absence is absence, and it must
	// not be reported as a failure the source did not report.
	ValuePresent  bool `protobuf:"varint,7,opt,name=value_present,json=valuePresent,proto3" json:"value_present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAItemPropertyResult) Reset() {
	*x = DAItemPropertyResult{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAItemPropertyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAItemPropertyResult) ProtoMessage() {}

func (x *DAItemPropertyResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAItemPropertyResult.ProtoReflect.Descriptor instead.
func (*DAItemPropertyResult) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{5}
}

func (x *DAItemPropertyResult) GetPropertyId() uint32 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *DAItemPropertyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DAItemPropertyResult) GetDataType() *DAVarType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *DAItemPropertyResult) GetValue() *DAScalarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DAItemPropertyResult) GetHresult() *DAHRESULT {
	if x != nil {
		return x.Hresult
	}
	return nil
}

func (x *DAItemPropertyResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DAItemPropertyResult) GetValuePresent() bool {
	if x != nil {
		return x.ValuePresent
	}
	return false
}

type DAStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAStatusRequest) Reset() {
	*x = DAStatusRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAStatusRequest) ProtoMessage() {}

func (x *DAStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAStatusRequest.ProtoReflect.Descriptor instead.
func (*DAStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{6}
}

type DAStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeState  string                 `protobuf:"bytes,1,opt,name=runtime_state,json=runtimeState,proto3" json:"runtime_state,omitempty"`
	Source        *DASource              `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Capabilities  *DACapabilities        `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	WriteEnabled  bool                   `protobuf:"varint,4,opt,name=write_enabled,json=writeEnabled,proto3" json:"write_enabled,omitempty"`
	Runtime       *DARuntimeStatus       `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Frontend      *DAGRPCFrontendStatus  `protobuf:"bytes,6,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAStatusResponse) Reset() {
	*x = DAStatusResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAStatusResponse) ProtoMessage() {}

func (x *DAStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAStatusResponse.ProtoReflect.Descriptor instead.
func (*DAStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{7}
}

func (x *DAStatusResponse) GetRuntimeState() string {
	if x != nil {
		return x.RuntimeState
	}
	return ""
}

func (x *DAStatusResponse) GetSource() *DASource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DAStatusResponse) GetCapabilities() *DACapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DAStatusResponse) GetWriteEnabled() bool {
	if x != nil {
		return x.WriteEnabled
	}
	return false
}

func (x *DAStatusResponse) GetRuntime() *DARuntimeStatus {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *DAStatusResponse) GetFrontend() *DAGRPCFrontendStatus {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type DASource struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProgId               string                 `protobuf:"bytes,1,opt,name=prog_id,json=progId,proto3" json:"prog_id,omitempty"`
	Clsid                string                 `protobuf:"bytes,2,opt,name=clsid,proto3" json:"clsid,omitempty"`
	ConnectionGeneration uint64                 `protobuf:"varint,3,opt,name=connection_generation,json=connectionGeneration,proto3" json:"connection_generation,omitempty"`
	LastError            *DASourceError         `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DASource) Reset() {
	*x = DASource{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASource) ProtoMessage() {}

func (x *DASource) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASource.ProtoReflect.Descriptor instead.
func (*DASource) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{8}
}

func (x *DASource) GetProgId() string {
	if x != nil {
		return x.ProgId
	}
	return ""
}

func (x *DASource) GetClsid() string {
	if x != nil {
		return x.Clsid
	}
	return ""
}

func (x *DASource) GetConnectionGeneration() uint64 {
	if x != nil {
		return x.ConnectionGeneration
	}
	return 0
}

func (x *DASource) GetLastError() *DASourceError {
	if x != nil {
		return x.LastError
	}
	return nil
}

type DASourceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Hresult       *DAHRESULT             `protobuf:"bytes,2,opt,name=hresult,proto3" json:"hresult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASourceError) Reset() {
	*x = DASourceError{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASourceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASourceError) ProtoMessage() {}

func (x *DASourceError) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASourceError.ProtoReflect.Descriptor instead.
func (*DASourceError) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{9}
}

func (x *DASourceError) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DASourceError) GetHresult() *DAHRESULT {
	if x != nil {
		return x.Hresult
	}
	return nil
}

type DACapabilities struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Browse    string                 `protobuf:"bytes,1,opt,name=browse,proto3" json:"browse,omitempty"`
	Read      bool                   `protobuf:"varint,2,opt,name=read,proto3" json:"read,omitempty"`
	Write     bool                   `protobuf:"varint,3,opt,name=write,proto3" json:"write,omitempty"`
	Subscribe bool                   `protobuf:"varint,4,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	// Whether the source implements IOPCItemProperties, which OPC 10000-8
	// Table A.1 is mapped from. Like browse it is "supported", "unsupported" or
	// "unavailable": a source that has not been asked is not one that said no.
	Properties    string `protobuf:"bytes,5,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DACapabilities) Reset() {
	*x = DACapabilities{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DACapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DACapabilities) ProtoMessage() {}

func (x *DACapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DACapabilities.ProtoReflect.Descriptor instead.
func (*DACapabilities) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{10}
}

func (x *DACapabilities) GetBrowse() string {
	if x != nil {
		return x.Browse
	}
	return ""
}

func (x *DACapabilities) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *DACapabilities) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

func (x *DACapabilities) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *DACapabilities) GetProperties() string {
	if x != nil {
		return x.Properties
	}
	return ""
}

type DARuntimeStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueueDepth     uint32                 `protobuf:"varint,1,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	ReconnectCount uint64                 `protobuf:"varint,2,opt,name=reconnect_count,json=reconnectCount,proto3" json:"reconnect_count,omitempty"`
	DegradedReason string                 `protobuf:"bytes,3,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`
	// subscription_count is the number of DA groups the runtime currently holds
	// for subscriptions. It returns to zero when a Subscribe stream ends.
	SubscriptionCount uint32 `protobuf:"varint,4,opt,name=subscription_count,json=subscriptionCount,proto3" json:"subscription_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DARuntimeStatus) Reset() {
	*x = DARuntimeStatus{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DARuntimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DARuntimeStatus) ProtoMessage() {}

func (x *DARuntimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DARuntimeStatus.ProtoReflect.Descriptor instead.
func (*DARuntimeStatus) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{11}
}

func (x *DARuntimeStatus) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *DARuntimeStatus) GetReconnectCount() uint64 {
	if x != nil {
		return x.ReconnectCount
	}
	return 0
}

func (x *DARuntimeStatus) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *DARuntimeStatus) GetSubscriptionCount() uint32 {
	if x != nil {
		return x.SubscriptionCount
	}
	return 0
}

type DAGRPCFrontendStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listening     bool                   `protobuf:"varint,1,opt,name=listening,proto3" json:"listening,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAGRPCFrontendStatus) Reset() {
	*x = DAGRPCFrontendStatus{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGRPCFrontendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGRPCFrontendStatus) ProtoMessage() {}

func (x *DAGRPCFrontendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGRPCFrontendStatus.ProtoReflect.Descriptor instead.
func (*DAGRPCFrontendStatus) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{12}
}

func (x *DAGRPCFrontendStatus) GetListening() bool {
	if x != nil {
		return x.Listening
	}
	return false
}

type DABrowseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Filter        DABrowseFilter         `protobuf:"varint,2,opt,name=filter,proto3,enum=opcda.access.v1.DABrowseFilter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DABrowseRequest) Reset() {
	*x = DABrowseRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DABrowseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DABrowseRequest) ProtoMessage() {}

func (x *DABrowseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DABrowseRequest.ProtoReflect.Descriptor instead.
func (*DABrowseRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{13}
}

func (x *DABrowseRequest) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DABrowseRequest) GetFilter() DABrowseFilter {
	if x != nil {
		return x.Filter
	}
	return DABrowseFilter_DA_BROWSE_FILTER_ALL
}

type DABrowseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	Entries       []*DABrowseEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DABrowseResponse) Reset() {
	*x = DABrowseResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DABrowseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DABrowseResponse) ProtoMessage() {}

func (x *DABrowseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DABrowseResponse.ProtoReflect.Descriptor instead.
func (*DABrowseResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{14}
}

func (x *DABrowseResponse) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DABrowseResponse) GetEntries() []*DABrowseEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DABrowseEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              DABrowseEntryKind      `protobuf:"varint,1,opt,name=kind,proto3,enum=opcda.access.v1.DABrowseEntryKind" json:"kind,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ItemId            string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemIdPresent     bool                   `protobuf:"varint,4,opt,name=item_id_present,json=itemIdPresent,proto3" json:"item_id_present,omitempty"`
	CanonicalDataType *DAVarType             `protobuf:"bytes,5,opt,name=canonical_data_type,json=canonicalDataType,proto3" json:"canonical_data_type,omitempty"`
	AccessRights      *DAAccessRights        `protobuf:"bytes,6,opt,name=access_rights,json=accessRights,proto3" json:"access_rights,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DABrowseEntry) Reset() {
	*x = DABrowseEntry{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DABrowseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DABrowseEntry) ProtoMessage() {}

func (x *DABrowseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DABrowseEntry.ProtoReflect.Descriptor instead.
func (*DABrowseEntry) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{15}
}

func (x *DABrowseEntry) GetKind() DABrowseEntryKind {
	if x != nil {
		return x.Kind
	}
	return DABrowseEntryKind_DA_BROWSE_ENTRY_KIND_UNSPECIFIED
}

func (x *DABrowseEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DABrowseEntry) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DABrowseEntry) GetItemIdPresent() bool {
	if x != nil {
		return x.ItemIdPresent
	}
	return false
}

func (x *DABrowseEntry) GetCanonicalDataType() *DAVarType {
	if x != nil {
		return x.CanonicalDataType
	}
	return nil
}

func (x *DABrowseEntry) GetAccessRights() *DAAccessRights {
	if x != nil {
		return x.AccessRights
	}
	return nil
}

type DAReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        DADataSource           `protobuf:"varint,1,opt,name=source,proto3,enum=opcda.access.v1.DADataSource" json:"source,omitempty"`
	Items         []*DAReadItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAReadRequest) Reset() {
	*x = DAReadRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAReadRequest) ProtoMessage() {}

func (x *DAReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAReadRequest.ProtoReflect.Descriptor instead.
func (*DAReadRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{16}
}

func (x *DAReadRequest) GetSource() DADataSource {
	if x != nil {
		return x.Source
	}
	return DADataSource_DA_DATA_SOURCE_DEVICE
}

func (x *DAReadRequest) GetItems() []*DAReadItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DAReadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAReadItem) Reset() {
	*x = DAReadItem{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAReadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAReadItem) ProtoMessage() {}

func (x *DAReadItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAReadItem.ProtoReflect.Descriptor instead.
func (*DAReadItem) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{17}
}

func (x *DAReadItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type DAReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DAReadResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAReadResponse) Reset() {
	*x = DAReadResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAReadResponse) ProtoMessage() {}

func (x *DAReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAReadResponse.ProtoReflect.Descriptor instead.
func (*DAReadResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{18}
}

func (x *DAReadResponse) GetResults() []*DAReadResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DAReadResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ItemId               string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Ok                   bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	DataType             *DAVarType             `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	CanonicalDataType    *DAVarType             `protobuf:"bytes,4,opt,name=canonical_data_type,json=canonicalDataType,proto3" json:"canonical_data_type,omitempty"`
	Value                *DAScalarValue         `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	QualityRaw           uint32                 `protobuf:"varint,6,opt,name=quality_raw,json=qualityRaw,proto3" json:"quality_raw,omitempty"`
	QualityPresent       bool                   `protobuf:"varint,7,opt,name=quality_present,json=qualityPresent,proto3" json:"quality_present,omitempty"`
	TimestampUnixSeconds int64                  `protobuf:"varint,8,opt,name=timestamp_unix_seconds,json=timestampUnixSeconds,proto3" json:"timestamp_unix_seconds,omitempty"`
	TimestampNanos       int32                  `protobuf:"varint,9,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	TimestampPresent     bool                   `protobuf:"varint,10,opt,name=timestamp_present,json=timestampPresent,proto3" json:"timestamp_present,omitempty"`
	Hresult              *DAHRESULT             `protobuf:"bytes,11,opt,name=hresult,proto3" json:"hresult,omitempty"`
	AccessRights         *DAAccessRights        `protobuf:"bytes,12,opt,name=access_rights,json=accessRights,proto3" json:"access_rights,omitempty"`
	ErrorCode            string                 `protobuf:"bytes,13,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DAReadResult) Reset() {
	*x = DAReadResult{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAReadResult) ProtoMessage() {}

func (x *DAReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAReadResult.ProtoReflect.Descriptor instead.
func (*DAReadResult) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{19}
}

func (x *DAReadResult) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DAReadResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DAReadResult) GetDataType() *DAVarType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *DAReadResult) GetCanonicalDataType() *DAVarType {
	if x != nil {
		return x.CanonicalDataType
	}
	return nil
}

func (x *DAReadResult) GetValue() *DAScalarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DAReadResult) GetQualityRaw() uint32 {
	if x != nil {
		return x.QualityRaw
	}
	return 0
}

func (x *DAReadResult) GetQualityPresent() bool {
	if x != nil {
		return x.QualityPresent
	}
	return false
}

func (x *DAReadResult) GetTimestampUnixSeconds() int64 {
	if x != nil {
		return x.TimestampUnixSeconds
	}
	return 0
}

func (x *DAReadResult) GetTimestampNanos() int32 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

func (x *DAReadResult) GetTimestampPresent() bool {
	if x != nil {
		return x.TimestampPresent
	}
	return false
}

func (x *DAReadResult) GetHresult() *DAHRESULT {
	if x != nil {
		return x.Hresult
	}
	return nil
}

func (x *DAReadResult) GetAccessRights() *DAAccessRights {
	if x != nil {
		return x.AccessRights
	}
	return nil
}

func (x *DAReadResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type DAWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DAWriteItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAWriteRequest) Reset() {
	*x = DAWriteRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAWriteRequest) ProtoMessage() {}

func (x *DAWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAWriteRequest.ProtoReflect.Descriptor instead.
func (*DAWriteRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{20}
}

func (x *DAWriteRequest) GetItems() []*DAWriteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DAWriteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	DataType      *DAVarType             `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Value         *DAScalarValue         `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAWriteItem) Reset() {
	*x = DAWriteItem{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAWriteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAWriteItem) ProtoMessage() {}

func (x *DAWriteItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAWriteItem.ProtoReflect.Descriptor instead.
func (*DAWriteItem) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{21}
}

func (x *DAWriteItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DAWriteItem) GetDataType() *DAVarType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *DAWriteItem) GetValue() *DAScalarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type DAWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DAWriteResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAWriteResponse) Reset() {
	*x = DAWriteResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAWriteResponse) ProtoMessage() {}

func (x *DAWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAWriteResponse.ProtoReflect.Descriptor instead.
func (*DAWriteResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{22}
}

func (x *DAWriteResponse) GetResults() []*DAWriteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DAWriteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Hresult       *DAHRESULT             `protobuf:"bytes,3,opt,name=hresult,proto3" json:"hresult,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAWriteResult) Reset() {
	*x = DAWriteResult{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAWriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAWriteResult) ProtoMessage() {}

func (x *DAWriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAWriteResult.ProtoReflect.Descriptor instead.
func (*DAWriteResult) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{23}
}

func (x *DAWriteResult) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DAWriteResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DAWriteResult) GetHresult() *DAHRESULT {
	if x != nil {
		return x.Hresult
	}
	return nil
}

func (x *DAWriteResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type DASubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*DASubscribeItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// requested_update_rate_ms is the DA group's dwRequestedUpdateRate. The
	// server answers with its own revised rate, which is reported unchanged.
	RequestedUpdateRateMs uint32 `protobuf:"varint,2,opt,name=requested_update_rate_ms,json=requestedUpdateRateMs,proto3" json:"requested_update_rate_ms,omitempty"`
	// percent_deadband is the DA group's pPercentDeadband. Zero omits it.
	PercentDeadband float32 `protobuf:"fixed32,3,opt,name=percent_deadband,json=percentDeadband,proto3" json:"percent_deadband,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DASubscribeRequest) Reset() {
	*x = DASubscribeRequest{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASubscribeRequest) ProtoMessage() {}

func (x *DASubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASubscribeRequest.ProtoReflect.Descriptor instead.
func (*DASubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{24}
}

func (x *DASubscribeRequest) GetItems() []*DASubscribeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DASubscribeRequest) GetRequestedUpdateRateMs() uint32 {
	if x != nil {
		return x.RequestedUpdateRateMs
	}
	return 0
}

func (x *DASubscribeRequest) GetPercentDeadband() float32 {
	if x != nil {
		return x.PercentDeadband
	}
	return 0
}

type DASubscribeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASubscribeItem) Reset() {
	*x = DASubscribeItem{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASubscribeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASubscribeItem) ProtoMessage() {}

func (x *DASubscribeItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASubscribeItem.ProtoReflect.Descriptor instead.
func (*DASubscribeItem) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{25}
}

func (x *DASubscribeItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// The first stream message is always `created`; every later message is an
// `update`.
type DASubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*DASubscribeResponse_Created
	//	*DASubscribeResponse_Update
	Message       isDASubscribeResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASubscribeResponse) Reset() {
	*x = DASubscribeResponse{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASubscribeResponse) ProtoMessage() {}

func (x *DASubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASubscribeResponse.ProtoReflect.Descriptor instead.
func (*DASubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{26}
}

func (x *DASubscribeResponse) GetMessage() isDASubscribeResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DASubscribeResponse) GetCreated() *DASubscriptionCreated {
	if x != nil {
		if x, ok := x.Message.(*DASubscribeResponse_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *DASubscribeResponse) GetUpdate() *DASubscriptionUpdate {
	if x != nil {
		if x, ok := x.Message.(*DASubscribeResponse_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isDASubscribeResponse_Message interface {
	isDASubscribeResponse_Message()
}

type DASubscribeResponse_Created struct {
	Created *DASubscriptionCreated `protobuf:"bytes,1,opt,name=created,proto3,oneof"`
}

type DASubscribeResponse_Update struct {
	Update *DASubscriptionUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*DASubscribeResponse_Created) isDASubscribeResponse_Message() {}

func (*DASubscribeResponse_Update) isDASubscribeResponse_Message() {}

type DASubscriptionCreated struct {
	state                 protoimpl.MessageState      `protogen:"open.v1"`
	SubscriptionId        string                      `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ConnectionGeneration  uint64                      `protobuf:"varint,2,opt,name=connection_generation,json=connectionGeneration,proto3" json:"connection_generation,omitempty"`
	RequestedUpdateRateMs uint32                      `protobuf:"varint,3,opt,name=requested_update_rate_ms,json=requestedUpdateRateMs,proto3" json:"requested_update_rate_ms,omitempty"`
	RevisedUpdateRateMs   uint32                      `protobuf:"varint,4,opt,name=revised_update_rate_ms,json=revisedUpdateRateMs,proto3" json:"revised_update_rate_ms,omitempty"`
	PercentDeadband       float32                     `protobuf:"fixed32,5,opt,name=percent_deadband,json=percentDeadband,proto3" json:"percent_deadband,omitempty"`
	Items                 []*DASubscriptionItemStatus `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	ActiveItemCount       uint32                      `protobuf:"varint,7,opt,name=active_item_count,json=activeItemCount,proto3" json:"active_item_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DASubscriptionCreated) Reset() {
	*x = DASubscriptionCreated{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASubscriptionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASubscriptionCreated) ProtoMessage() {}

func (x *DASubscriptionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASubscriptionCreated.ProtoReflect.Descriptor instead.
func (*DASubscriptionCreated) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{27}
}

func (x *DASubscriptionCreated) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *DASubscriptionCreated) GetConnectionGeneration() uint64 {
	if x != nil {
		return x.ConnectionGeneration
	}
	return 0
}

func (x *DASubscriptionCreated) GetRequestedUpdateRateMs() uint32 {
	if x != nil {
		return x.RequestedUpdateRateMs
	}
	return 0
}

func (x *DASubscriptionCreated) GetRevisedUpdateRateMs() uint32 {
	if x != nil {
		return x.RevisedUpdateRateMs
	}
	return 0
}

func (x *DASubscriptionCreated) GetPercentDeadband() float32 {
	if x != nil {
		return x.PercentDeadband
	}
	return 0
}

func (x *DASubscriptionCreated) GetItems() []*DASubscriptionItemStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DASubscriptionCreated) GetActiveItemCount() uint32 {
	if x != nil {
		return x.ActiveItemCount
	}
	return 0
}

// DASubscriptionItemStatus preserves the exact per-item AddItems outcome. A
// failed item keeps its source HRESULT instead of failing the subscription.
type DASubscriptionItemStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemId            string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Active            bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	CanonicalDataType *DAVarType             `protobuf:"bytes,3,opt,name=canonical_data_type,json=canonicalDataType,proto3" json:"canonical_data_type,omitempty"`
	AccessRights      *DAAccessRights        `protobuf:"bytes,4,opt,name=access_rights,json=accessRights,proto3" json:"access_rights,omitempty"`
	Hresult           *DAHRESULT             `protobuf:"bytes,5,opt,name=hresult,proto3" json:"hresult,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DASubscriptionItemStatus) Reset() {
	*x = DASubscriptionItemStatus{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASubscriptionItemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASubscriptionItemStatus) ProtoMessage() {}

func (x *DASubscriptionItemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASubscriptionItemStatus.ProtoReflect.Descriptor instead.
func (*DASubscriptionItemStatus) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{28}
}

func (x *DASubscriptionItemStatus) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DASubscriptionItemStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DASubscriptionItemStatus) GetCanonicalDataType() *DAVarType {
	if x != nil {
		return x.CanonicalDataType
	}
	return nil
}

func (x *DASubscriptionItemStatus) GetAccessRights() *DAAccessRights {
	if x != nil {
		return x.AccessRights
	}
	return nil
}

func (x *DASubscriptionItemStatus) GetHresult() *DAHRESULT {
	if x != nil {
		return x.Hresult
	}
	return nil
}

func (x *DASubscriptionItemStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// DASubscriptionUpdate carries one coalesced OPC DA notification batch. OPC DA
// reports only the latest cache value between update-rate ticks, so a consumer
// slower than the revised rate observes the same values it would have observed
// at a slower requested rate. Values reuse DAReadResult so a subscribed value
// and a device Read value cannot drift apart.
type DASubscriptionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*DAReadResult        `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASubscriptionUpdate) Reset() {
	*x = DASubscriptionUpdate{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASubscriptionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASubscriptionUpdate) ProtoMessage() {}

func (x *DASubscriptionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASubscriptionUpdate.ProtoReflect.Descriptor instead.
func (*DASubscriptionUpdate) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{29}
}

func (x *DASubscriptionUpdate) GetValues() []*DAReadResult {
	if x != nil {
		return x.Values
	}
	return nil
}

type DAVarType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           uint32                 `protobuf:"varint,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Array         bool                   `protobuf:"varint,3,opt,name=array,proto3" json:"array,omitempty"`
	Byref         bool                   `protobuf:"varint,4,opt,name=byref,proto3" json:"byref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAVarType) Reset() {
	*x = DAVarType{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAVarType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAVarType) ProtoMessage() {}

func (x *DAVarType) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAVarType.ProtoReflect.Descriptor instead.
func (*DAVarType) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{30}
}

func (x *DAVarType) GetRaw() uint32 {
	if x != nil {
		return x.Raw
	}
	return 0
}

func (x *DAVarType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DAVarType) GetArray() bool {
	if x != nil {
		return x.Array
	}
	return false
}

func (x *DAVarType) GetByref() bool {
	if x != nil {
		return x.Byref
	}
	return false
}

type DAAccessRights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           uint32                 `protobuf:"varint,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Read          bool                   `protobuf:"varint,2,opt,name=read,proto3" json:"read,omitempty"`
	Write         bool                   `protobuf:"varint,3,opt,name=write,proto3" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAAccessRights) Reset() {
	*x = DAAccessRights{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAAccessRights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAAccessRights) ProtoMessage() {}

func (x *DAAccessRights) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAAccessRights.ProtoReflect.Descriptor instead.
func (*DAAccessRights) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{31}
}

func (x *DAAccessRights) GetRaw() uint32 {
	if x != nil {
		return x.Raw
	}
	return 0
}

func (x *DAAccessRights) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *DAAccessRights) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

type DAHRESULT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"zigzag32,1,opt,name=value,proto3" json:"value,omitempty"`
	Raw           uint32                 `protobuf:"fixed32,2,opt,name=raw,proto3" json:"raw,omitempty"`
	Hex           string                 `protobuf:"bytes,3,opt,name=hex,proto3" json:"hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAHRESULT) Reset() {
	*x = DAHRESULT{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAHRESULT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAHRESULT) ProtoMessage() {}

func (x *DAHRESULT) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAHRESULT.ProtoReflect.Descriptor instead.
func (*DAHRESULT) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{32}
}

func (x *DAHRESULT) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DAHRESULT) GetRaw() uint32 {
	if x != nil {
		return x.Raw
	}
	return 0
}

func (x *DAHRESULT) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type DAScalarValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*DAScalarValue_EmptyOrNull
	//	*DAScalarValue_I1Value
	//	*DAScalarValue_Ui1Value
	//	*DAScalarValue_I2Value
	//	*DAScalarValue_Ui2Value
	//	*DAScalarValue_I4Value
	//	*DAScalarValue_Ui4Value
	//	*DAScalarValue_I8Value
	//	*DAScalarValue_Ui8Value
	//	*DAScalarValue_R4Value
	//	*DAScalarValue_R8Value
	//	*DAScalarValue_BoolValue
	//	*DAScalarValue_BstrValue
	//	*DAScalarValue_ErrorValue
	//	*DAScalarValue_IntValue
	//	*DAScalarValue_UintValue
	Value         isDAScalarValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAScalarValue) Reset() {
	*x = DAScalarValue{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAScalarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAScalarValue) ProtoMessage() {}

func (x *DAScalarValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAScalarValue.ProtoReflect.Descriptor instead.
func (*DAScalarValue) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{33}
}

func (x *DAScalarValue) GetValue() isDAScalarValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DAScalarValue) GetEmptyOrNull() bool {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_EmptyOrNull); ok {
			return x.EmptyOrNull
		}
	}
	return false
}

func (x *DAScalarValue) GetI1Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_I1Value); ok {
			return x.I1Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetUi1Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_Ui1Value); ok {
			return x.Ui1Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetI2Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_I2Value); ok {
			return x.I2Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetUi2Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_Ui2Value); ok {
			return x.Ui2Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetI4Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_I4Value); ok {
			return x.I4Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetUi4Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_Ui4Value); ok {
			return x.Ui4Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetI8Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_I8Value); ok {
			return x.I8Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetUi8Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_Ui8Value); ok {
			return x.Ui8Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetR4Value() float32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_R4Value); ok {
			return x.R4Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetR8Value() float64 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_R8Value); ok {
			return x.R8Value
		}
	}
	return 0
}

func (x *DAScalarValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *DAScalarValue) GetBstrValue() string {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_BstrValue); ok {
			return x.BstrValue
		}
	}
	return ""
}

func (x *DAScalarValue) GetErrorValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_ErrorValue); ok {
			return x.ErrorValue
		}
	}
	return 0
}

func (x *DAScalarValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *DAScalarValue) GetUintValue() uint32 {
	if x != nil {
		if x, ok := x.Value.(*DAScalarValue_UintValue); ok {
			return x.UintValue
		}
	}
	return 0
}

type isDAScalarValue_Value interface {
	isDAScalarValue_Value()
}

type DAScalarValue_EmptyOrNull struct {
	EmptyOrNull bool `protobuf:"varint,1,opt,name=empty_or_null,json=emptyOrNull,proto3,oneof"`
}

type DAScalarValue_I1Value struct {
	I1Value int32 `protobuf:"zigzag32,2,opt,name=i1_value,json=i1Value,proto3,oneof"`
}

type DAScalarValue_Ui1Value struct {
	Ui1Value uint32 `protobuf:"varint,3,opt,name=ui1_value,json=ui1Value,proto3,oneof"`
}

type DAScalarValue_I2Value struct {
	I2Value int32 `protobuf:"zigzag32,4,opt,name=i2_value,json=i2Value,proto3,oneof"`
}

type DAScalarValue_Ui2Value struct {
	Ui2Value uint32 `protobuf:"varint,5,opt,name=ui2_value,json=ui2Value,proto3,oneof"`
}

type DAScalarValue_I4Value struct {
	I4Value int32 `protobuf:"zigzag32,6,opt,name=i4_value,json=i4Value,proto3,oneof"`
}

type DAScalarValue_Ui4Value struct {
	Ui4Value uint32 `protobuf:"varint,7,opt,name=ui4_value,json=ui4Value,proto3,oneof"`
}

type DAScalarValue_I8Value struct {
	I8Value int64 `protobuf:"zigzag64,8,opt,name=i8_value,json=i8Value,proto3,oneof"`
}

type DAScalarValue_Ui8Value struct {
	Ui8Value uint64 `protobuf:"varint,9,opt,name=ui8_value,json=ui8Value,proto3,oneof"`
}

type DAScalarValue_R4Value struct {
	R4Value float32 `protobuf:"fixed32,10,opt,name=r4_value,json=r4Value,proto3,oneof"`
}

type DAScalarValue_R8Value struct {
	R8Value float64 `protobuf:"fixed64,11,opt,name=r8_value,json=r8Value,proto3,oneof"`
}

type DAScalarValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,12,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type DAScalarValue_BstrValue struct {
	BstrValue string `protobuf:"bytes,13,opt,name=bstr_value,json=bstrValue,proto3,oneof"`
}

type DAScalarValue_ErrorValue struct {
	ErrorValue int32 `protobuf:"zigzag32,14,opt,name=error_value,json=errorValue,proto3,oneof"`
}

type DAScalarValue_IntValue struct {
	IntValue int32 `protobuf:"zigzag32,15,opt,name=int_value,json=intValue,proto3,oneof"`
}

type DAScalarValue_UintValue struct {
	UintValue uint32 `protobuf:"varint,16,opt,name=uint_value,json=uintValue,proto3,oneof"`
}

func (*DAScalarValue_EmptyOrNull) isDAScalarValue_Value() {}

func (*DAScalarValue_I1Value) isDAScalarValue_Value() {}

func (*DAScalarValue_Ui1Value) isDAScalarValue_Value() {}

func (*DAScalarValue_I2Value) isDAScalarValue_Value() {}

func (*DAScalarValue_Ui2Value) isDAScalarValue_Value() {}

func (*DAScalarValue_I4Value) isDAScalarValue_Value() {}

func (*DAScalarValue_Ui4Value) isDAScalarValue_Value() {}

func (*DAScalarValue_I8Value) isDAScalarValue_Value() {}

func (*DAScalarValue_Ui8Value) isDAScalarValue_Value() {}

func (*DAScalarValue_R4Value) isDAScalarValue_Value() {}

func (*DAScalarValue_R8Value) isDAScalarValue_Value() {}

func (*DAScalarValue_BoolValue) isDAScalarValue_Value() {}

func (*DAScalarValue_BstrValue) isDAScalarValue_Value() {}

func (*DAScalarValue_ErrorValue) isDAScalarValue_Value() {}

func (*DAScalarValue_IntValue) isDAScalarValue_Value() {}

func (*DAScalarValue_UintValue) isDAScalarValue_Value() {}

// DAOperationError is attached to request-level gRPC status errors. Per-item
// source failures remain in successful batch responses instead.
type DAOperationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         string                 `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Hresult       *DAHRESULT             `protobuf:"bytes,5,opt,name=hresult,proto3" json:"hresult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAOperationError) Reset() {
	*x = DAOperationError{}
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAOperationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAOperationError) ProtoMessage() {}

func (x *DAOperationError) ProtoReflect() protoreflect.Message {
	mi := &file_api_opcda_v1_opcda_access_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAOperationError.ProtoReflect.Descriptor instead.
func (*DAOperationError) Descriptor() ([]byte, []int) {
	return file_api_opcda_v1_opcda_access_proto_rawDescGZIP(), []int{34}
}

func (x *DAOperationError) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *DAOperationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DAOperationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DAOperationError) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DAOperationError) GetHresult() *DAHRESULT {
	if x != nil {
		return x.Hresult
	}
	return nil
}

var File_api_opcda_v1_opcda_access_proto protoreflect.FileDescriptor

const file_api_opcda_v1_opcda_access_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/opcda/v1/opcda_access.proto\x12\x0fopcda.access.v1\";\n" +
	" DAAvailableItemPropertiesRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\x82\x01\n" +
	"!DAAvailableItemPropertiesResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12D\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2$.opcda.access.v1.DAAvailablePropertyR\n" +
	"properties\"\x91\x01\n" +
	"\x13DAAvailableProperty\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\rR\n" +
	"propertyId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\tdata_type\x18\x03 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\bdataType\"U\n" +
	"\x17DAItemPropertiesRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12!\n" +
	"\fproperty_ids\x18\x02 \x03(\rR\vpropertyIds\"t\n" +
	"\x18DAItemPropertiesResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12?\n" +
	"\aresults\x18\x02 \x03(\v2%.opcda.access.v1.DAItemPropertyResultR\aresults\"\xb0\x02\n" +
	"\x14DAItemPropertyResult\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\rR\n" +
	"propertyId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x127\n" +
	"\tdata_type\x18\x03 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\bdataType\x124\n" +
	"\x05value\x18\x04 \x01(\v2\x1e.opcda.access.v1.DAScalarValueR\x05value\x124\n" +
	"\ahresult\x18\x05 \x01(\v2\x1a.opcda.access.v1.DAHRESULTR\ahresult\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rvalue_present\x18\a \x01(\bR\fvaluePresent\"\x11\n" +
	"\x0fDAStatusRequest\"\xd3\x02\n" +
	"\x10DAStatusResponse\x12#\n" +
	"\rruntime_state\x18\x01 \x01(\tR\fruntimeState\x121\n" +
	"\x06source\x18\x02 \x01(\v2\x19.opcda.access.v1.DASourceR\x06source\x12C\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1f.opcda.access.v1.DACapabilitiesR\fcapabilities\x12#\n" +
	"\rwrite_enabled\x18\x04 \x01(\bR\fwriteEnabled\x12:\n" +
	"\aruntime\x18\x05 \x01(\v2 .opcda.access.v1.DARuntimeStatusR\aruntime\x12A\n" +
	"\bfrontend\x18\x06 \x01(\v2%.opcda.access.v1.DAGRPCFrontendStatusR\bfrontend\"\xad\x01\n" +
	"\bDASource\x12\x17\n" +
	"\aprog_id\x18\x01 \x01(\tR\x06progId\x12\x14\n" +
	"\x05clsid\x18\x02 \x01(\tR\x05clsid\x123\n" +
	"\x15connection_generation\x18\x03 \x01(\x04R\x14connectionGeneration\x12=\n" +
	"\n" +
	"last_error\x18\x04 \x01(\v2\x1e.opcda.access.v1.DASourceErrorR\tlastError\"c\n" +
	"\rDASourceError\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x124\n" +
	"\ahresult\x18\x02 \x01(\v2\x1a.opcda.access.v1.DAHRESULTR\ahresult\"\x90\x01\n" +
	"\x0eDACapabilities\x12\x16\n" +
	"\x06browse\x18\x01 \x01(\tR\x06browse\x12\x12\n" +
	"\x04read\x18\x02 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x03 \x01(\bR\x05write\x12\x1c\n" +
	"\tsubscribe\x18\x04 \x01(\bR\tsubscribe\x12\x1e\n" +
	"\n" +
	"properties\x18\x05 \x01(\tR\n" +
	"properties\"\xb3\x01\n" +
	"\x0fDARuntimeStatus\x12\x1f\n" +
	"\vqueue_depth\x18\x01 \x01(\rR\n" +
	"queueDepth\x12'\n" +
	"\x0freconnect_count\x18\x02 \x01(\x04R\x0ereconnectCount\x12'\n" +
	"\x0fdegraded_reason\x18\x03 \x01(\tR\x0edegradedReason\x12-\n" +
	"\x12subscription_count\x18\x04 \x01(\rR\x11subscriptionCount\"4\n" +
	"\x14DAGRPCFrontendStatus\x12\x1c\n" +
	"\tlistening\x18\x01 \x01(\bR\tlistening\"^\n" +
	"\x0fDABrowseRequest\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x127\n" +
	"\x06filter\x18\x02 \x01(\x0e2\x1f.opcda.access.v1.DABrowseFilterR\x06filter\"`\n" +
	"\x10DABrowseResponse\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.opcda.access.v1.DABrowseEntryR\aentries\"\xae\x02\n" +
	"\rDABrowseEntry\x126\n" +
	"\x04kind\x18\x01 \x01(\x0e2\".opcda.access.v1.DABrowseEntryKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12&\n" +
	"\x0fitem_id_present\x18\x04 \x01(\bR\ritemIdPresent\x12J\n" +
	"\x13canonical_data_type\x18\x05 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\x11canonicalDataType\x12D\n" +
	"\raccess_rights\x18\x06 \x01(\v2\x1f.opcda.access.v1.DAAccessRightsR\faccessRights\"y\n" +
	"\rDAReadRequest\x125\n" +
	"\x06source\x18\x01 \x01(\x0e2\x1d.opcda.access.v1.DADataSourceR\x06source\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.opcda.access.v1.DAReadItemR\x05items\"%\n" +
	"\n" +
	"DAReadItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"I\n" +
	"\x0eDAReadResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.opcda.access.v1.DAReadResultR\aresults\"\xe3\x04\n" +
	"\fDAReadResult\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x127\n" +
	"\tdata_type\x18\x03 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\bdataType\x12J\n" +
	"\x13canonical_data_type\x18\x04 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\x11canonicalDataType\x124\n" +
	"\x05value\x18\x05 \x01(\v2\x1e.opcda.access.v1.DAScalarValueR\x05value\x12\x1f\n" +
	"\vquality_raw\x18\x06 \x01(\rR\n" +
	"qualityRaw\x12'\n" +
	"\x0fquality_present\x18\a \x01(\bR\x0equalityPresent\x124\n" +
	"\x16timestamp_unix_seconds\x18\b \x01(\x03R\x14timestampUnixSeconds\x12'\n" +
	"\x0ftimestamp_nanos\x18\t \x01(\x05R\x0etimestampNanos\x12+\n" +
	"\x11timestamp_present\x18\n" +
	" \x01(\bR\x10timestampPresent\x124\n" +
	"\ahresult\x18\v \x01(\v2\x1a.opcda.access.v1.DAHRESULTR\ahresult\x12D\n" +
	"\raccess_rights\x18\f \x01(\v2\x1f.opcda.access.v1.DAAccessRightsR\faccessRights\x12\x1d\n" +
	"\n" +
	"error_code\x18\r \x01(\tR\terrorCode\"D\n" +
	"\x0eDAWriteRequest\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.opcda.access.v1.DAWriteItemR\x05items\"\x95\x01\n" +
	"\vDAWriteItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x127\n" +
	"\tdata_type\x18\x02 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\bdataType\x124\n" +
	"\x05value\x18\x03 \x01(\v2\x1e.opcda.access.v1.DAScalarValueR\x05value\"K\n" +
	"\x0fDAWriteResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.opcda.access.v1.DAWriteResultR\aresults\"\x8d\x01\n" +
	"\rDAWriteResult\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x124\n" +
	"\ahresult\x18\x03 \x01(\v2\x1a.opcda.access.v1.DAHRESULTR\ahresult\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xb0\x01\n" +
	"\x12DASubscribeRequest\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .opcda.access.v1.DASubscribeItemR\x05items\x127\n" +
	"\x18requested_update_rate_ms\x18\x02 \x01(\rR\x15requestedUpdateRateMs\x12)\n" +
	"\x10percent_deadband\x18\x03 \x01(\x02R\x0fpercentDeadband\"*\n" +
	"\x0fDASubscribeItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\xa5\x01\n" +
	"\x13DASubscribeResponse\x12B\n" +
	"\acreated\x18\x01 \x01(\v2&.opcda.access.v1.DASubscriptionCreatedH\x00R\acreated\x12?\n" +
	"\x06update\x18\x02 \x01(\v2%.opcda.access.v1.DASubscriptionUpdateH\x00R\x06updateB\t\n" +
	"\amessage\"\xfb\x02\n" +
	"\x15DASubscriptionCreated\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x123\n" +
	"\x15connection_generation\x18\x02 \x01(\x04R\x14connectionGeneration\x127\n" +
	"\x18requested_update_rate_ms\x18\x03 \x01(\rR\x15requestedUpdateRateMs\x123\n" +
	"\x16revised_update_rate_ms\x18\x04 \x01(\rR\x13revisedUpdateRateMs\x12)\n" +
	"\x10percent_deadband\x18\x05 \x01(\x02R\x0fpercentDeadband\x12?\n" +
	"\x05items\x18\x06 \x03(\v2).opcda.access.v1.DASubscriptionItemStatusR\x05items\x12*\n" +
	"\x11active_item_count\x18\a \x01(\rR\x0factiveItemCount\"\xb2\x02\n" +
	"\x18DASubscriptionItemStatus\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12J\n" +
	"\x13canonical_data_type\x18\x03 \x01(\v2\x1a.opcda.access.v1.DAVarTypeR\x11canonicalDataType\x12D\n" +
	"\raccess_rights\x18\x04 \x01(\v2\x1f.opcda.access.v1.DAAccessRightsR\faccessRights\x124\n" +
	"\ahresult\x18\x05 \x01(\v2\x1a.opcda.access.v1.DAHRESULTR\ahresult\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\"M\n" +
	"\x14DASubscriptionUpdate\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.opcda.access.v1.DAReadResultR\x06values\"]\n" +
	"\tDAVarType\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\rR\x03raw\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05array\x18\x03 \x01(\bR\x05array\x12\x14\n" +
	"\x05byref\x18\x04 \x01(\bR\x05byref\"L\n" +
	"\x0eDAAccessRights\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\rR\x03raw\x12\x12\n" +
	"\x04read\x18\x02 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x03 \x01(\bR\x05write\"E\n" +
	"\tDAHRESULT\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x11R\x05value\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\aR\x03raw\x12\x10\n" +
	"\x03hex\x18\x03 \x01(\tR\x03hex\"\x8d\x04\n" +
	"\rDAScalarValue\x12$\n" +
	"\rempty_or_null\x18\x01 \x01(\bH\x00R\vemptyOrNull\x12\x1b\n" +
	"\bi1_value\x18\x02 \x01(\x11H\x00R\ai1Value\x12\x1d\n" +
	"\tui1_value\x18\x03 \x01(\rH\x00R\bui1Value\x12\x1b\n" +
	"\bi2_value\x18\x04 \x01(\x11H\x00R\ai2Value\x12\x1d\n" +
	"\tui2_value\x18\x05 \x01(\rH\x00R\bui2Value\x12\x1b\n" +
	"\bi4_value\x18\x06 \x01(\x11H\x00R\ai4Value\x12\x1d\n" +
	"\tui4_value\x18\a \x01(\rH\x00R\bui4Value\x12\x1b\n" +
	"\bi8_value\x18\b \x01(\x12H\x00R\ai8Value\x12\x1d\n" +
	"\tui8_value\x18\t \x01(\x04H\x00R\bui8Value\x12\x1b\n" +
	"\br4_value\x18\n" +
	" \x01(\x02H\x00R\ar4Value\x12\x1b\n" +
	"\br8_value\x18\v \x01(\x01H\x00R\ar8Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\f \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"bstr_value\x18\r \x01(\tH\x00R\tbstrValue\x12!\n" +
	"\verror_value\x18\x0e \x01(\x11H\x00R\n" +
	"errorValue\x12\x1d\n" +
	"\tint_value\x18\x0f \x01(\x11H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"uint_value\x18\x10 \x01(\rH\x00R\tuintValueB\a\n" +
	"\x05value\"\xaa\x01\n" +
	"\x10DAOperationError\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\tR\x05layer\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x124\n" +
	"\ahresult\x18\x05 \x01(\v2\x1a.opcda.access.v1.DAHRESULTR\ahresult*b\n" +
	"\x0eDABrowseFilter\x12\x18\n" +
	"\x14DA_BROWSE_FILTER_ALL\x10\x00\x12\x1b\n" +
	"\x17DA_BROWSE_FILTER_BRANCH\x10\x01\x12\x19\n" +
	"\x15DA_BROWSE_FILTER_ITEM\x10\x02*y\n" +
	"\x11DABrowseEntryKind\x12$\n" +
	" DA_BROWSE_ENTRY_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDA_BROWSE_ENTRY_KIND_BRANCH\x10\x01\x12\x1d\n" +
	"\x19DA_BROWSE_ENTRY_KIND_ITEM\x10\x02*)\n" +
	"\fDADataSource\x12\x19\n" +
	"\x15DA_DATA_SOURCE_DEVICE\x10\x002\x84\x05\n" +
	"\vOPCDAAccess\x12M\n" +
	"\x06Status\x12 .opcda.access.v1.DAStatusRequest\x1a!.opcda.access.v1.DAStatusResponse\x12M\n" +
	"\x06Browse\x12 .opcda.access.v1.DABrowseRequest\x1a!.opcda.access.v1.DABrowseResponse\x12G\n" +
	"\x04Read\x12\x1e.opcda.access.v1.DAReadRequest\x1a\x1f.opcda.access.v1.DAReadResponse\x12J\n" +
	"\x05Write\x12\x1f.opcda.access.v1.DAWriteRequest\x1a .opcda.access.v1.DAWriteResponse\x12X\n" +
	"\tSubscribe\x12#.opcda.access.v1.DASubscribeRequest\x1a$.opcda.access.v1.DASubscribeResponse0\x01\x12\x80\x01\n" +
	"\x17AvailableItemProperties\x121.opcda.access.v1.DAAvailableItemPropertiesRequest\x1a2.opcda.access.v1.DAAvailableItemPropertiesResponse\x12e\n" +
	"\x0eItemProperties\x12(.opcda.access.v1.DAItemPropertiesRequest\x1a).opcda.access.v1.DAItemPropertiesResponseB@Z>github.com/east-true/opcda-access-adapter/api/opcda/v1;opcdav1b\x06proto3"

var (
	file_api_opcda_v1_opcda_access_proto_rawDescOnce sync.Once
	file_api_opcda_v1_opcda_access_proto_rawDescData []byte
)

func file_api_opcda_v1_opcda_access_proto_rawDescGZIP() []byte {
	file_api_opcda_v1_opcda_access_proto_rawDescOnce.Do(func() {
		file_api_opcda_v1_opcda_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_opcda_v1_opcda_access_proto_rawDesc), len(file_api_opcda_v1_opcda_access_proto_rawDesc)))
	})
	return file_api_opcda_v1_opcda_access_proto_rawDescData
}

var file_api_opcda_v1_opcda_access_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_opcda_v1_opcda_access_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_opcda_v1_opcda_access_proto_goTypes = []any{
	(DABrowseFilter)(0),                       // 0: opcda.access.v1.DABrowseFilter
	(DABrowseEntryKind)(0),                    // 1: opcda.access.v1.DABrowseEntryKind
	(DADataSource)(0),                         // 2: opcda.access.v1.DADataSource
	(*DAAvailableItemPropertiesRequest)(nil),  // 3: opcda.access.v1.DAAvailableItemPropertiesRequest
	(*DAAvailableItemPropertiesResponse)(nil), // 4: opcda.access.v1.DAAvailableItemPropertiesResponse
	(*DAAvailableProperty)(nil),               // 5: opcda.access.v1.DAAvailableProperty
	(*DAItemPropertiesRequest)(nil),           // 6: opcda.access.v1.DAItemPropertiesRequest
	(*DAItemPropertiesResponse)(nil),          // 7: opcda.access.v1.DAItemPropertiesResponse
	(*DAItemPropertyResult)(nil),              // 8: opcda.access.v1.DAItemPropertyResult
	(*DAStatusRequest)(nil),                   // 9: opcda.access.v1.DAStatusRequest
	(*DAStatusResponse)(nil),                  // 10: opcda.access.v1.DAStatusResponse
	(*DASource)(nil),                          // 11: opcda.access.v1.DASource
	(*DASourceError)(nil),                     // 12: opcda.access.v1.DASourceError
	(*DACapabilities)(nil),                    // 13: opcda.access.v1.DACapabilities
	(*DARuntimeStatus)(nil),                   // 14: opcda.access.v1.DARuntimeStatus
	(*DAGRPCFrontendStatus)(nil),              // 15: opcda.access.v1.DAGRPCFrontendStatus
	(*DABrowseRequest)(nil),                   // 16: opcda.access.v1.DABrowseRequest
	(*DABrowseResponse)(nil),                  // 17: opcda.access.v1.DABrowseResponse
	(*DABrowseEntry)(nil),                     // 18: opcda.access.v1.DABrowseEntry
	(*DAReadRequest)(nil),                     // 19: opcda.access.v1.DAReadRequest
	(*DAReadItem)(nil),                        // 20: opcda.access.v1.DAReadItem
	(*DAReadResponse)(nil),                    // 21: opcda.access.v1.DAReadResponse
	(*DAReadResult)(nil),                      // 22: opcda.access.v1.DAReadResult
	(*DAWriteRequest)(nil),                    // 23: opcda.access.v1.DAWriteRequest
	(*DAWriteItem)(nil),                       // 24: opcda.access.v1.DAWriteItem
	(*DAWriteResponse)(nil),                   // 25: opcda.access.v1.DAWriteResponse
	(*DAWriteResult)(nil),                     // 26: opcda.access.v1.DAWriteResult
	(*DASubscribeRequest)(nil),                // 27: opcda.access.v1.DASubscribeRequest
	(*DASubscribeItem)(nil),                   // 28: opcda.access.v1.DASubscribeItem
	(*DASubscribeResponse)(nil),               // 29: opcda.access.v1.DASubscribeResponse
	(*DASubscriptionCreated)(nil),             // 30: opcda.access.v1.DASubscriptionCreated
	(*DASubscriptionItemStatus)(nil),          // 31: opcda.access.v1.DASubscriptionItemStatus
	(*DASubscriptionUpdate)(nil),              // 32: opcda.access.v1.DASubscriptionUpdate
	(*DAVarType)(nil),                         // 33: opcda.access.v1.DAVarType
	(*DAAccessRights)(nil),                    // 34: opcda.access.v1.DAAccessRights
	(*DAHRESULT)(nil),                         // 35: opcda.access.v1.DAHRESULT
	(*DAScalarValue)(nil),                     // 36: opcda.access.v1.DAScalarValue
	(*DAOperationError)(nil),                  // 37: opcda.access.v1.DAOperationError
}
var file_api_opcda_v1_opcda_access_proto_depIdxs = []int32{
	5,  // 0: opcda.access.v1.DAAvailableItemPropertiesResponse.properties:type_name -> opcda.access.v1.DAAvailableProperty
	33, // 1: opcda.access.v1.DAAvailableProperty.data_type:type_name -> opcda.access.v1.DAVarType
	8,  // 2: opcda.access.v1.DAItemPropertiesResponse.results:type_name -> opcda.access.v1.DAItemPropertyResult
	33, // 3: opcda.access.v1.DAItemPropertyResult.data_type:type_name -> opcda.access.v1.DAVarType
	36, // 4: opcda.access.v1.DAItemPropertyResult.value:type_name -> opcda.access.v1.DAScalarValue
	35, // 5: opcda.access.v1.DAItemPropertyResult.hresult:type_name -> opcda.access.v1.DAHRESULT
	11, // 6: opcda.access.v1.DAStatusResponse.source:type_name -> opcda.access.v1.DASource
	13, // 7: opcda.access.v1.DAStatusResponse.capabilities:type_name -> opcda.access.v1.DACapabilities
	14, // 8: opcda.access.v1.DAStatusResponse.runtime:type_name -> opcda.access.v1.DARuntimeStatus
	15, // 9: opcda.access.v1.DAStatusResponse.frontend:type_name -> opcda.access.v1.DAGRPCFrontendStatus
	12, // 10: opcda.access.v1.DASource.last_error:type_name -> opcda.access.v1.DASourceError
	35, // 11: opcda.access.v1.DASourceError.hresult:type_name -> opcda.access.v1.DAHRESULT
	0,  // 12: opcda.access.v1.DABrowseRequest.filter:type_name -> opcda.access.v1.DABrowseFilter
	18, // 13: opcda.access.v1.DABrowseResponse.entries:type_name -> opcda.access.v1.DABrowseEntry
	1,  // 14: opcda.access.v1.DABrowseEntry.kind:type_name -> opcda.access.v1.DABrowseEntryKind
	33, // 15: opcda.access.v1.DABrowseEntry.canonical_data_type:type_name -> opcda.access.v1.DAVarType
	34, // 16: opcda.access.v1.DABrowseEntry.access_rights:type_name -> opcda.access.v1.DAAccessRights
	2,  // 17: opcda.access.v1.DAReadRequest.source:type_name -> opcda.access.v1.DADataSource
	20, // 18: opcda.access.v1.DAReadRequest.items:type_name -> opcda.access.v1.DAReadItem
	22, // 19: opcda.access.v1.DAReadResponse.results:type_name -> opcda.access.v1.DAReadResult
	33, // 20: opcda.access.v1.DAReadResult.data_type:type_name -> opcda.access.v1.DAVarType
	33, // 21: opcda.access.v1.DAReadResult.canonical_data_type:type_name -> opcda.access.v1.DAVarType
	36, // 22: opcda.access.v1.DAReadResult.value:type_name -> opcda.access.v1.DAScalarValue
	35, // 23: opcda.access.v1.DAReadResult.hresult:type_name -> opcda.access.v1.DAHRESULT
	34, // 24: opcda.access.v1.DAReadResult.access_rights:type_name -> opcda.access.v1.DAAccessRights
	24, // 25: opcda.access.v1.DAWriteRequest.items:type_name -> opcda.access.v1.DAWriteItem
	33, // 26: opcda.access.v1.DAWriteItem.data_type:type_name -> opcda.access.v1.DAVarType
	36, // 27: opcda.access.v1.DAWriteItem.value:type_name -> opcda.access.v1.DAScalarValue
	26, // 28: opcda.access.v1.DAWriteResponse.results:type_name -> opcda.access.v1.DAWriteResult
	35, // 29: opcda.access.v1.DAWriteResult.hresult:type_name -> opcda.access.v1.DAHRESULT
	28, // 30: opcda.access.v1.DASubscribeRequest.items:type_name -> opcda.access.v1.DASubscribeItem
	30, // 31: opcda.access.v1.DASubscribeResponse.created:type_name -> opcda.access.v1.DASubscriptionCreated
	32, // 32: opcda.access.v1.DASubscribeResponse.update:type_name -> opcda.access.v1.DASubscriptionUpdate
	31, // 33: opcda.access.v1.DASubscriptionCreated.items:type_name -> opcda.access.v1.DASubscriptionItemStatus
	33, // 34: opcda.access.v1.DASubscriptionItemStatus.canonical_data_type:type_name -> opcda.access.v1.DAVarType
	34, // 35: opcda.access.v1.DASubscriptionItemStatus.access_rights:type_name -> opcda.access.v1.DAAccessRights
	35, // 36: opcda.access.v1.DASubscriptionItemStatus.hresult:type_name -> opcda.access.v1.DAHRESULT
	22, // 37: opcda.access.v1.DASubscriptionUpdate.values:type_name -> opcda.access.v1.DAReadResult
	35, // 38: opcda.access.v1.DAOperationError.hresult:type_name -> opcda.access.v1.DAHRESULT
	9,  // 39: opcda.access.v1.OPCDAAccess.Status:input_type -> opcda.access.v1.DAStatusRequest
	16, // 40: opcda.access.v1.OPCDAAccess.Browse:input_type -> opcda.access.v1.DABrowseRequest
	19, // 41: opcda.access.v1.OPCDAAccess.Read:input_type -> opcda.access.v1.DAReadRequest
	23, // 42: opcda.access.v1.OPCDAAccess.Write:input_type -> opcda.access.v1.DAWriteRequest
	27, // 43: opcda.access.v1.OPCDAAccess.Subscribe:input_type -> opcda.access.v1.DASubscribeRequest
	3,  // 44: opcda.access.v1.OPCDAAccess.AvailableItemProperties:input_type -> opcda.access.v1.DAAvailableItemPropertiesRequest
	6,  // 45: opcda.access.v1.OPCDAAccess.ItemProperties:input_type -> opcda.access.v1.DAItemPropertiesRequest
	10, // 46: opcda.access.v1.OPCDAAccess.Status:output_type -> opcda.access.v1.DAStatusResponse
	17, // 47: opcda.access.v1.OPCDAAccess.Browse:output_type -> opcda.access.v1.DABrowseResponse
	21, // 48: opcda.access.v1.OPCDAAccess.Read:output_type -> opcda.access.v1.DAReadResponse
	25, // 49: opcda.access.v1.OPCDAAccess.Write:output_type -> opcda.access.v1.DAWriteResponse
	29, // 50: opcda.access.v1.OPCDAAccess.Subscribe:output_type -> opcda.access.v1.DASubscribeResponse
	4,  // 51: opcda.access.v1.OPCDAAccess.AvailableItemProperties:output_type -> opcda.access.v1.DAAvailableItemPropertiesResponse
	7,  // 52: opcda.access.v1.OPCDAAccess.ItemProperties:output_type -> opcda.access.v1.DAItemPropertiesResponse
	46, // [46:53] is the sub-list for method output_type
	39, // [39:46] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_api_opcda_v1_opcda_access_proto_init() }
func file_api_opcda_v1_opcda_access_proto_init() {
	if File_api_opcda_v1_opcda_access_proto != nil {
		return
	}
	file_api_opcda_v1_opcda_access_proto_msgTypes[26].OneofWrappers = []any{
		(*DASubscribeResponse_Created)(nil),
		(*DASubscribeResponse_Update)(nil),
	}
	file_api_opcda_v1_opcda_access_proto_msgTypes[33].OneofWrappers = []any{
		(*DAScalarValue_EmptyOrNull)(nil),
		(*DAScalarValue_I1Value)(nil),
		(*DAScalarValue_Ui1Value)(nil),
		(*DAScalarValue_I2Value)(nil),
		(*DAScalarValue_Ui2Value)(nil),
		(*DAScalarValue_I4Value)(nil),
		(*DAScalarValue_Ui4Value)(nil),
		(*DAScalarValue_I8Value)(nil),
		(*DAScalarValue_Ui8Value)(nil),
		(*DAScalarValue_R4Value)(nil),
		(*DAScalarValue_R8Value)(nil),
		(*DAScalarValue_BoolValue)(nil),
		(*DAScalarValue_BstrValue)(nil),
		(*DAScalarValue_ErrorValue)(nil),
		(*DAScalarValue_IntValue)(nil),
		(*DAScalarValue_UintValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_opcda_v1_opcda_access_proto_rawDesc), len(file_api_opcda_v1_opcda_access_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_opcda_v1_opcda_access_proto_goTypes,
		DependencyIndexes: file_api_opcda_v1_opcda_access_proto_depIdxs,
		EnumInfos:         file_api_opcda_v1_opcda_access_proto_enumTypes,
		MessageInfos:      file_api_opcda_v1_opcda_access_proto_msgTypes,
	}.Build()
	File_api_opcda_v1_opcda_access_proto = out.File
	file_api_opcda_v1_opcda_access_proto_goTypes = nil
	file_api_opcda_v1_opcda_access_proto_depIdxs = nil
}
