// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: api/opcda/v1/opcda_access.proto

package opcdav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OPCDAAccess_Status_FullMethodName = "/opcda.access.v1.OPCDAAccess/Status"
	OPCDAAccess_Browse_FullMethodName = "/opcda.access.v1.OPCDAAccess/Browse"
	OPCDAAccess_Read_FullMethodName   = "/opcda.access.v1.OPCDAAccess/Read"
	OPCDAAccess_Write_FullMethodName  = "/opcda.access.v1.OPCDAAccess/Write"
)

// OPCDAAccessClient is the client API for OPCDAAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OPCDAAccess exposes one explicitly configured local OPC DA source.
type OPCDAAccessClient interface {
	Status(ctx context.Context, in *DAStatusRequest, opts ...grpc.CallOption) (*DAStatusResponse, error)
	Browse(ctx context.Context, in *DABrowseRequest, opts ...grpc.CallOption) (*DABrowseResponse, error)
	Read(ctx context.Context, in *DAReadRequest, opts ...grpc.CallOption) (*DAReadResponse, error)
	Write(ctx context.Context, in *DAWriteRequest, opts ...grpc.CallOption) (*DAWriteResponse, error)
}

type oPCDAAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewOPCDAAccessClient(cc grpc.ClientConnInterface) OPCDAAccessClient {
	return &oPCDAAccessClient{cc}
}

func (c *oPCDAAccessClient) Status(ctx context.Context, in *DAStatusRequest, opts ...grpc.CallOption) (*DAStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAStatusResponse)
	err := c.cc.Invoke(ctx, OPCDAAccess_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oPCDAAccessClient) Browse(ctx context.Context, in *DABrowseRequest, opts ...grpc.CallOption) (*DABrowseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DABrowseResponse)
	err := c.cc.Invoke(ctx, OPCDAAccess_Browse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oPCDAAccessClient) Read(ctx context.Context, in *DAReadRequest, opts ...grpc.CallOption) (*DAReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAReadResponse)
	err := c.cc.Invoke(ctx, OPCDAAccess_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oPCDAAccessClient) Write(ctx context.Context, in *DAWriteRequest, opts ...grpc.CallOption) (*DAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DAWriteResponse)
	err := c.cc.Invoke(ctx, OPCDAAccess_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OPCDAAccessServer is the server API for OPCDAAccess service.
// All implementations must embed UnimplementedOPCDAAccessServer
// for forward compatibility.
//
// OPCDAAccess exposes one explicitly configured local OPC DA source.
type OPCDAAccessServer interface {
	Status(context.Context, *DAStatusRequest) (*DAStatusResponse, error)
	Browse(context.Context, *DABrowseRequest) (*DABrowseResponse, error)
	Read(context.Context, *DAReadRequest) (*DAReadResponse, error)
	Write(context.Context, *DAWriteRequest) (*DAWriteResponse, error)
	mustEmbedUnimplementedOPCDAAccessServer()
}

// UnimplementedOPCDAAccessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOPCDAAccessServer struct{}

func (UnimplementedOPCDAAccessServer) Status(context.Context, *DAStatusRequest) (*DAStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedOPCDAAccessServer) Browse(context.Context, *DABrowseRequest) (*DABrowseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Browse not implemented")
}
func (UnimplementedOPCDAAccessServer) Read(context.Context, *DAReadRequest) (*DAReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedOPCDAAccessServer) Write(context.Context, *DAWriteRequest) (*DAWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedOPCDAAccessServer) mustEmbedUnimplementedOPCDAAccessServer() {}
func (UnimplementedOPCDAAccessServer) testEmbeddedByValue()                     {}

// UnsafeOPCDAAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OPCDAAccessServer will
// result in compilation errors.
type UnsafeOPCDAAccessServer interface {
	mustEmbedUnimplementedOPCDAAccessServer()
}

func RegisterOPCDAAccessServer(s grpc.ServiceRegistrar, srv OPCDAAccessServer) {
	// If the following call panics, it indicates UnimplementedOPCDAAccessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OPCDAAccess_ServiceDesc, srv)
}

func _OPCDAAccess_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DAStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OPCDAAccessServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OPCDAAccess_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OPCDAAccessServer).Status(ctx, req.(*DAStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OPCDAAccess_Browse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DABrowseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OPCDAAccessServer).Browse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OPCDAAccess_Browse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OPCDAAccessServer).Browse(ctx, req.(*DABrowseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OPCDAAccess_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DAReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OPCDAAccessServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OPCDAAccess_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OPCDAAccessServer).Read(ctx, req.(*DAReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OPCDAAccess_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DAWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OPCDAAccessServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OPCDAAccess_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OPCDAAccessServer).Write(ctx, req.(*DAWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OPCDAAccess_ServiceDesc is the grpc.ServiceDesc for OPCDAAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OPCDAAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opcda.access.v1.OPCDAAccess",
	HandlerType: (*OPCDAAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _OPCDAAccess_Status_Handler,
		},
		{
			MethodName: "Browse",
			Handler:    _OPCDAAccess_Browse_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _OPCDAAccess_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _OPCDAAccess_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/opcda/v1/opcda_access.proto",
}
